### ISSUE TITLE
For V1.0.2

### ISSUE THREAD

**Issue by PiMaV** [CodeSchmiedeHGW/BLITZ#14]
- [x] Pop up window when doing cost intensiv stuff like: Loading and calculating 
- [x] LUT / Options dialog 60 /40 or such
- [ ] when using Normalization, H/V are not updated
- [x] ROI handles should be bigger as well
- [x] Mask has two handles in the lower right corner
- [x] Show "Calculating" Window only when its actually calculating. not when saved is loaded

**Comment by irkri** [comment]
> * [ ]  when using Normalization, H/V are not updated

This is probably easier to do if we reimplement Normalization as a whole. Let's move this to #18.

> * [x]  Show "Calculating" Window only when its actually calculating. not when saved is loaded

Let's just change "Calculating" to "Loading [operation]" and we are done. Something else would mean to restructure the code a bit. This is just a simpler solution. :)

**Comment by PiMaV** [comment]
tested all of the addressed stuff. Can be closed
