### ISSUE TITLE
Performance / GPU

### ISSUE THREAD

**Issue by PiMaV** [CodeSchmiedeHGW/BLITZ#16]
These can be easily done:
pg.setConfigOptions(useNumba=True)
pg.setConfigOptions(useOpenGL=True)

this is a bit more complex:
(Maybe as an option to set in the ini File)
User needs to install cupy manually beforehands.
pg.setConfigOptions(useCupy=True) # Requires CUDA and CuPy ... Bad for small laptops

**Comment by irkri** [comment]
I don't think that any of these do something for BLITZ. Right now, we do all the heavy stuff on our own. Pyqtgraph only shows the images we manipulate using plain numpy. 
Calculating the mean inside the ROI or the normalization stuff doesn't use numba either. (This is something that pyqtgraph handles.)

**Comment by PiMaV** [comment]
Lets drop this for now.

**Comment by PiMaV** [comment]
Lets drop this for now

**Comment by PiMaV** [comment]
Can we make (more) use of GPU? building a special cupy version? Might not be worth the trouble for BLITZ, but for heavy pca use it might be.

**Comment by PiMaV** [comment]
Will be taken care when dealing with the PCA properly
