### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by irkri** [CodeSchmiedeHGW/BLITZ#18]
We should change the normalization toolbox from `pyqtgraph` to our own version.
Some notes:
- Their normalization always copies all the currently loaded (maybe masked) images before manipulating.
- Something doesn't work with _Subtraction_ and _Divide_.
- Because only the shown images are manipulated, masking, flipping, transposing and all other operations cannot be combined with the current normalization.

Before implementing anything, what kind of normalization do we really need?

**Comment by PiMaV** [comment]
- Subtraction
- Division.

For now its fine to just use a single image. Either we mimic the behavior of the timeline (so being able to select a range of images to build the mean), or we build our own interface.

For now, its enough to select the "operation" and pass either:
- a number (indicating the number of the image that should be used)
- or filename
- or something "preselected" like "mean" or "max", "min", "std"
