### ISSUE TITLE
Minor Bugs / Improvements

### ISSUE THREAD

**Issue by PiMaV** [CodeSchmiedeHGW/BLITZ#26]
# Bugs:
- x,y,value is not updating when hovering with mouse over a pixel and then using arrows to scroll through the timeline
- Subtract Mean (and other manipulations) should get a waiting signal, to show the system is still responsive
- Measure Tool: Pixels can be any int (atm its only up to 99); [mm] can have more than two digits.
- File extensions seem to be case sensetive

# Feature:
- Max. Ram Settings should be saved in ini 
- add third Parameter for the Crosshair ("Time"). So we can "average" over time as well

**Comment by irkri** [comment]
The last point is not clear to me.
Is this a feature request for the normalization? Subtracting the mean of the crosshair for all time steps?

**Comment by PiMaV** [comment]
> The last point is not clear to me. Is this a feature request for the normalization? Subtracting the mean of the crosshair for all time steps?

This is an idea for 3D (time) arrays. at the moment we do H&V averaging per image. It would be also of interest to do this for time as well. However this would be similar to use the mean image and then use H&V

-> lets forget this for now and close this
