### ISSUE TITLE
Bugs from 1.1.0

### ISSUE THREAD

**Issue by PiMaV** [CodeSchmiedeHGW/BLITZ#28]
- Switching back from "Max" to "-" does not show loading
- Switching between "reduction" Modes centers Crosshair (should NOT happen)
- "Filename" in the Statusbar should NOT be seperated (Or better: Configurable in INIT) 
- Font (i.e X,Y,V in Statusbar) : Bigger (maybbe also Init)
- If a folder has subfolders (or other files), although 99% are images, we cant load the folder
- we should "Show" somewhere the loading options (in red or such). So the user sees, that a REDUCED or A SUBSET was loaded

**Comment by irkri** [comment]
All things should be fixed here.
- The Crosshair only gets centered when something happens with the size of the images loaded.
- Filename is now cut off at the beginning if its longer than a preset option (given in the .ini file).
- The font size of the status bar is configurable in the ini.
- In a folder, a majority vote decides which file extension gets loaded (i.e. 100 '.png', 10 '.txt' and 20 '.npy' files will lead to all '.png' files being loaded.
- The log now supports different colors (we use white (standard), red (error) and green (good-to-know)).

**Comment by PiMaV** [comment]
Uii... Colorful logs...das muss ich nachher mal testen

**Comment by irkri** [comment]
I now send the options to the log when loading new images. It is already shown, if a subset of the images are loaded (i.e. 'Loading 10/20 images').

**Comment by PiMaV** [comment]
Looking good.
Can be closed
