### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by PiMaV** [CodeSchmiedeHGW/BLITZ#30]
Small Issue:
- Grayscale is the norm. So when loading it, dont give a warning in yellow, just an info in green. 
DAU will cry...

PS:
Next meeting explain dim =4 :-)

**Comment by irkri** [comment]
I removed all warnings. The info is in the green box that comes with loading each dataset.
The dimensionality should be explained in the [walkthrough](/docs/walkthrough.md).

**Comment by PiMaV** [comment]
Works fine like this
